export type DomainErrorCode =
  | "PROFILE_PSEUDONYM_REQUIRED"
  | "PROFILE_PSEUDONYM_TOO_LONG"
  | "PROFILE_CONTEXT_TOO_LONG"
  | "PROJECT_TITLE_REQUIRED"
  | "PROJECT_TITLE_TOO_LONG"
  | "PROJECT_NOT_FOUND"
  | "MISSION_DEFINITION_INVALID"
  | "MISSION_NOT_FOUND"
  | "ACTIVITY_TEXT_REQUIRED"
  | "ACTIVITY_RESPONSE_NOT_FOUND"
  | "EVIDENCE_NOT_FOUND"
  | "EVIDENCE_TITLE_REQUIRED"
  | "EVIDENCE_SUMMARY_REQUIRED"
  | "PORTFOLIO_ITEM_NOT_FOUND"
  | "ACCESSIBILITY_PREFERENCES_INVALID"
  | "SCHEMA_VERSION_UNSUPPORTED"
  | "DUPLICATE_IDENTIFIER"
  | "INVALID_STATE_TRANSITION"
  | "BINARY_CONTENT_PROHIBITED"
  | "HUMAN_DECISION_REQUIRED"
  | "PORTFOLIO_EVIDENCE_NOT_FOUND"
  | "PORTFOLIO_DUPLICATE_EVIDENCE"
  | "REFLECTION_PRIVACY_INVALID"
  | "EXPORT_SELECTION_REQUIRED"
  | "DEFERRED_CAPABILITY_ENABLED"
  | "IMPORT_UNEXPECTED_FIELD"
  | "LEGACY_MIGRATION_REQUIRED"
  | "GROUP_DATA_PROHIBITED"
  | "TIMESTAMP_ORDER_INVALID"
  | "AUTOMATED_DECISION_PROHIBITED";

export interface DomainError {
  readonly code: DomainErrorCode;
  readonly path: string;
  readonly safeMessage: string;
  readonly details?: Readonly<Record<string, unknown>>;
}
